//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsodAsgmnt5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICatalogService1")]
    public interface ICatalogService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService1/GetHotelDeals", ReplyAction="http://tempuri.org/ICatalogService1/GetHotelDealsResponse")]
        string[] GetHotelDeals(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService1/GetHotelDeals", ReplyAction="http://tempuri.org/ICatalogService1/GetHotelDealsResponse")]
        System.Threading.Tasks.Task<string[]> GetHotelDealsAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService1/GetCarDeals", ReplyAction="http://tempuri.org/ICatalogService1/GetCarDealsResponse")]
        string[] GetCarDeals(string city, string startDate, string endDate, string pickupTime, string dropoffTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogService1/GetCarDeals", ReplyAction="http://tempuri.org/ICatalogService1/GetCarDealsResponse")]
        System.Threading.Tasks.Task<string[]> GetCarDealsAsync(string city, string startDate, string endDate, string pickupTime, string dropoffTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogService1Channel : DsodAsgmnt5.ServiceReference1.ICatalogService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogService1Client : System.ServiceModel.ClientBase<DsodAsgmnt5.ServiceReference1.ICatalogService1>, DsodAsgmnt5.ServiceReference1.ICatalogService1 {
        
        public CatalogService1Client() {
        }
        
        public CatalogService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetHotelDeals(string city) {
            return base.Channel.GetHotelDeals(city);
        }
        
        public System.Threading.Tasks.Task<string[]> GetHotelDealsAsync(string city) {
            return base.Channel.GetHotelDealsAsync(city);
        }
        
        public string[] GetCarDeals(string city, string startDate, string endDate, string pickupTime, string dropoffTime) {
            return base.Channel.GetCarDeals(city, startDate, endDate, pickupTime, dropoffTime);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCarDealsAsync(string city, string startDate, string endDate, string pickupTime, string dropoffTime) {
            return base.Channel.GetCarDealsAsync(city, startDate, endDate, pickupTime, dropoffTime);
        }
    }
}
